name: Loan-Request-Acceptance-Model-Pipeline
on: 
  push:
    branches:
    - main
jobs:
  run:
    runs-on: ubuntu-latest 
    container: docker://dvcorg/cml-py3:latest
    steps:
    - uses: actions/checkout@v2
    - name: cml_run
      env: 
        repo_token: ${{ secrets.ACCESS_TOKEN }}
      run: | 
        pip install -r requirements.txt
        python build_model.py

        # Write your CML report
        echo "## Model Metrics" >> report.md
        cat metrics.txt >> report.md

        echo "## Data Visualization" >> report.md
        cml-publish featureImportance.png --md >> report.md

        
        cml-send-comment report.md
    
